### PR TITLE
Added Amazon price tracker

### PR DESCRIPTION
**Pull request by YashKumar-17**
Python script for Amazon price tracker

### CODE REVIEW

**Comment by mpotane** [comment]
Please edit your PR bro it's empty atm.

**Comment by mpotane** [comment]
Once you're done open new issue for #hacktoberfest2022

**Comment by YashKumar-17** [comment]
Ohh, i guess might have been some issue, i will update it again.

**Comment by mpotane** [comment]
Closing this for now. You can submit another PR thank you!

**Pull request closed without merging**
